#!/usr/bin/env bash
# spec-map.sh — генератор карты корпуса спеков (LX).
#
# Детерминированно (без LLM) собирает specs/README.md: входная точка в корпус —
# таблица NNN · название · Type · Status · INV · дыры + mermaid-граф зависимостей
# (из front-matter `Depends on`). Перегенерируется в ритуале закрытия (/speckit.lx.close).
#
# Использование (в корне репозитория):
#   spec-map.sh                # пишет specs/README.md
#   SPECS_DIR=SPECS spec-map.sh
# Безопасность: НЕ перезапишет существующий README без маркера AUTOGENERATED.
set -euo pipefail

SPECS_DIR="${SPECS_DIR:-specs}"
OUT="$SPECS_DIR/README.md"
MARK="<!-- AUTOGENERATED by spec-map.sh — правки руками будут перезаписаны -->"

[ -d "$SPECS_DIR" ] || { echo "нет каталога $SPECS_DIR" >&2; exit 2; }
if [ -f "$OUT" ] && ! head -3 "$OUT" | grep -q "AUTOGENERATED by spec-map.sh"; then
  echo "ОТКАЗ: $OUT существует и не помечен AUTOGENERATED — не перезаписываю." >&2; exit 3
fi

tmp="$(mktemp)"
{
  echo "$MARK"
  echo "# Карта корпуса спеков"
  echo
  echo "> Генерируется \`spec-map.sh\` (lx-flow-ext); обновляется в ритуале закрытия. Не редактировать руками."
  echo
  echo "| SPEC | Название | Type | Status | INV | дыры\* |"
  echo "|------|----------|------|--------|-----|-------|"
} > "$tmp"

edges=""
for d in "$SPECS_DIR"/[0-9][0-9][0-9]-*/; do
  [ -d "$d" ] || continue
  f="$d/spec.md"; [ -f "$f" ] || continue
  nnn="$(basename "$d" | cut -c1-3)"
  name="$(basename "$d" | cut -c5-)"
  # заголовок: `# SPEC NNN — Title` → Title (fallback: имя папки)
  title="$(sed -n '1s/^# *SPEC[^—-]*[—-] *//p' "$f")"; [ -n "$title" ] || title="$name"
  # front-matter
  typ="$(grep -m1 '^\*\*Type:\*\*' "$f" | grep -oE '\(([FBRQ])\)' | tr -d '()' || true)"
  status="$(grep -m1 '^\*\*Status:\*\*' "$f" | sed 's/^\*\*Status:\*\* *//; s/ *[—-].*$//; s/\*\*//g' | cut -c1-24)"
  # INV: блоки в секции «Инварианты» spec.md (v4.3: «**INVn — …**»)
  inv="$(grep -cE '^\*\*INV[0-9]' "$f" || true)"
  # дыры покрытия: число перед 🔴/— в строке «Покрытие: N ✓ · M —» секции «Инварианты»
  holes="$(grep -m1 'Покрытие:' "$f" | grep -oE '· *[0-9]+ *(🔴|—)' | grep -oE '[0-9]+' | head -1 || true)"
  printf '| [%s](%s/spec.md) | %s | %s | %s | %s | %s |\n' \
    "$nnn" "$(basename "$d")" "$title" "${typ:-—}" "${status:-—}" "${inv:-0}" "${holes:-0}" >> "$tmp"
  # рёбра зависимостей из строки Depends on. Номера — любые NNN (корпус может быть 100+),
  # ложные срабатывания типа «бюджет $300» отсекаются двумя фильтрами:
  #   1) скобочные аннотации срезаются ДО парсинга (номера зависимостей стоят вне скобок);
  #   2) ребро добавляется только если папка спеки существует.
  deps="$(grep -m1 '^\*\*Depends on:\*\*' "$f" | sed 's/([^)]*)//g' | grep -oE '\b[0-9]{3}\b' | sort -u || true)"
  for dep in $deps; do
    [ "$dep" != "$nnn" ] && ls -d "$SPECS_DIR/$dep"-* >/dev/null 2>&1 \
      && edges="$edges  S$dep --> S$nnn"$'\n'
  done
done

{
  echo
  echo "\* дыры — из строки «Покрытие: N ✓ · M —/🔴» секции «Инварианты» spec.md."
  echo
  echo "## Граф зависимостей"
  echo
  echo '```mermaid'
  echo "graph LR"
  printf '%s' "$edges" | sort -u
  echo '```'
} >> "$tmp"

mv "$tmp" "$OUT"
n="$(grep -c '^| \[' "$OUT")"
echo "карта: $OUT — $n спеков, $(printf '%s' "$edges" | sort -u | grep -c . || true) рёбер"
